services:
  - type: web
    name: mks-store-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python simple_app.py
    pythonVersion: 3.8.18